
spring:

  application:
    name: demo-producer
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true  #?? ??????????
          initial-interval: 1000 #?????????????ms???1000
          multiplier: 1 #?????????????1?????????????????1
          max-attempts: 3 #?????????3
          stateless: true #????????true???????????false

    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated        # ???????????????
    publisher-returns: true #?????return????
server:
  port: 8080